const practiceTrials2 = [
    {"trial": 1, "fish1_p": "stimuli/bead_g.PNG", "fish2_p": "stimuli/blank.jpg", "fish3_p": "stimuli/blank.jpg", "fish4_p": "stimuli/blank.jpg", "fish5_p": "stimuli/blank.jpg", "pond_p": 2, "pond_p2": 3, "pond_p3": "right"},
    {"trial": 2, "fish1_p": "stimuli/bead_g.PNG", "fish2_p": "stimuli/bead_g.PNG", "fish3_p": "stimuli/blank.jpg", "fish4_p": "stimuli/blank.jpg", "fish5_p": "stimuli/blank.jpg", "pond_p": 2, "pond_p2": 3, "pond_p3": "right"},
    {"trial": 3, "fish1_p": "stimuli/bead_b.PNG", "fish2_p": "stimuli/bead_g.PNG", "fish3_p": "stimuli/bead_g.PNG", "fish4_p": "stimuli/blank.jpg", "fish5_p": "stimuli/blank.jpg", "pond_p": 2, "pond_p2": 3, "pond_p3": "right"},
    {"trial": 4, "fish1_p": "stimuli/bead_g.PNG", "fish2_p": "stimuli/bead_b.PNG", "fish3_p": "stimuli/bead_g.PNG", "fish4_p": "stimuli/bead_g.PNG", "fish5_p": "stimuli/blank.jpg", "pond_p": 2, "pond_p2": 3, "pond_p3": "right"},
    {"trial": 5, "fish1_p": "stimuli/bead_b.PNG", "fish2_p": "stimuli/bead_g.PNG", "fish3_p": "stimuli/bead_b.PNG", "fish4_p": "stimuli/bead_g.PNG", "fish5_p": "stimuli/bead_g.PNG", "pond_p": 2, "pond_p2": 3, "pond_p3": "right"},
    {"trial": 6, "fish1_p": "stimuli/bead_g.PNG", "fish2_p": "stimuli/bead_b.PNG", "fish3_p": "stimuli/bead_g.PNG", "fish4_p": "stimuli/bead_b.PNG", "fish5_p": "stimuli/bead_g.PNG", "pond_p": 2, "pond_p2": 3, "pond_p3": "right"},
    {"trial": 7, "fish1_p": "stimuli/bead_g.PNG", "fish2_p": "stimuli/bead_g.PNG", "fish3_p": "stimuli/bead_b.PNG", "fish4_p": "stimuli/bead_g.PNG", "fish5_p": "stimuli/bead_b.PNG", "pond_p": 2, "pond_p2": 3, "pond_p3": "right"},
    {"trial": 8, "fish1_p": "stimuli/bead_g.PNG", "fish2_p": "stimuli/bead_g.PNG", "fish3_p": "stimuli/bead_g.PNG", "fish4_p": "stimuli/bead_b.PNG", "fish5_p": "stimuli/bead_g.PNG", "pond_p": 2, "pond_p2": 3, "pond_p3": "right"},
    {"trial": 9, "fish1_p": "stimuli/bead_y.PNG", "fish2_p": "stimuli/bead_g.PNG", "fish3_p": "stimuli/bead_g.PNG", "fish4_p": "stimuli/bead_g.PNG", "fish5_p": "stimuli/bead_b.PNG", "pond_p": 1, "pond_p2": 2, "pond_p3": "up"},
    {"trial": 10, "fish1_p": "stimuli/bead_y.PNG", "fish2_p": "stimuli/bead_y.PNG", "fish3_p": "stimuli/bead_g.PNG", "fish4_p": "stimuli/bead_g.PNG", "fish5_p": "stimuli/bead_g.PNG", "pond_p": 1, "pond_p2": 2, "pond_p3": "up"},
    {"trial": 11, "fish1_p": "stimuli/bead_y.PNG", "fish2_p": "stimuli/bead_y.PNG", "fish3_p": "stimuli/bead_y.PNG", "fish4_p": "stimuli/bead_g.PNG", "fish5_p": "stimuli/bead_g.PNG", "pond_p": 1, "pond_p2": 2, "pond_p3": "up"},
    {"trial": 12, "fish1_p": "stimuli/bead_g.PNG", "fish2_p": "stimuli/bead_y.PNG", "fish3_p": "stimuli/bead_y.PNG", "fish4_p": "stimuli/bead_y.PNG", "fish5_p": "stimuli/bead_g.PNG", "pond_p": 1, "pond_p2": 2, "pond_p3": "up"},
    {"trial": 13, "fish1_p": "stimuli/bead_y.PNG", "fish2_p": "stimuli/bead_g.PNG", "fish3_p": "stimuli/bead_y.PNG", "fish4_p": "stimuli/bead_y.PNG", "fish5_p": "stimuli/bead_y.PNG", "pond_p": 1, "pond_p2": 2, "pond_p3": "up"},
    {"trial": 14, "fish1_p": "stimuli/bead_y.PNG", "fish2_p": "stimuli/bead_y.PNG", "fish3_p": "stimuli/bead_g.PNG", "fish4_p": "stimuli/bead_y.PNG", "fish5_p": "stimuli/bead_y.PNG", "pond_p": 1, "pond_p2": 2, "pond_p3": "up"},
    {"trial": 15, "fish1_p": "stimuli/bead_b.PNG", "fish2_p": "stimuli/bead_y.PNG", "fish3_p": "stimuli/bead_y.PNG", "fish4_p": "stimuli/bead_g.PNG", "fish5_p": "stimuli/bead_y.PNG", "pond_p": 1, "pond_p2": 2, "pond_p3": "up"}
];
